packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  typescript: ^5.7.3
  better-auth: ^1.4.3
  '@polar-sh/better-auth': ^1.5.0
  dotenv: ^17.2.3
  zod: ^4.1.13
  '@types/node': ^22.10.7
  react: ^19.2.0
  react-dom: ^19.2.0
  '@prisma/client': ^7.0.1
  pg: ^8.16.3
  '@types/react': ^19.2.7
  '@better-auth/expo': ^1.4.3
  '@orpc/client': '^1.12.0'
  '@orpc/contract': '^1.12.0'
  '@orpc/openapi-client': '^1.12.0'
  '@orpc/nest': '^1.12.0'
